### ISSUE TITLE
Unable to install MultiNest package (permissions issue)

### ISSUE THREAD

**Issue by ledwar04** [rubin-dp0/Support#39]
**Describe the bug**
I get a permissions error when trying to install the package MuiltNest. Ultimately, I am trying to use Bagpipes, an SED fitting code. https://bagpipes.readthedocs.io/en/latest/ which installs well with pip. However, it requires MuiltNest for full fuctionality. I am able to use conda to get Bagpipes. MultiNest, https://github.com/JohannesBuchner/MultiNest did not install with Conda or Pip or Mamba, so I git clone's it from github and followed the instructions to CMake and Make and Install the package.  cmake and make (after installing a few fortran dependancies and brew) work successfully, however the final step  <make install> provides the error, also given in the screenshot below:

"CMake Error at src/cmake_install.cmake:46 (file):
  file INSTALL cannot copy file "/home/ledwar04/MultiNest/lib/libmultinest.a"
  to "/usr/local/lib/libmultinest.a": Permission denied.
Call Stack (most recent call first):
  cmake_install.cmake:47 (include)

The instructions actually call to use <sudo make install> but when I do that I get the following error:
bash: sudo: command not found

**To Reproduce**
1. Go to https://bagpipes.readthedocs.io/en/latest/ 
2. Scroll down to Source and Installation and find the instructions following the text:
   In my experience, the sequence of commands necessary to install MultiNest on a mac (with Homebrew installed) is as follows:
   git clone https://github.com/JohannesBuchner/MultiNest
   brew install gcc49
  export DYLD_LIBRARY_PATH="/usr/local/bin/gcc-4.9:$DYLD_LIBRARY_PATH"
  cd MultiNest/build
  cmake ..
  make
  sudo make install
  cd ../..
  rm -r MultiNest

3. At the ,<sudo make install> step the error: 
bash: sudo: command not found

Comes up. If I then run <make install> instead, all of the building seems to work fine, but the final install step gives this error:

"CMake Error at src/cmake_install.cmake:46 (file):
  file INSTALL cannot copy file "/home/ledwar04/MultiNest/lib/libmultinest.a"
  to "/usr/local/lib/libmultinest.a": Permission denied.
Call Stack (most recent call first):
  cmake_install.cmake:47 (include)

**Expected behavior**
I expected this to install, so that I could continue on with my bagpipes install.

**Screenshots**
![MultiNest_install](https://user-images.githubusercontent.com/38015492/207685473-16660d01-bcfb-4eca-a9c0-ac4d3f5e664e.png)

**URL**
If applicable, cut and paste the URL from your browser at which the issue occurred
https://data.lsst.cloud/nb/user/ledwar04/lab/tree/SEDfitting

**Additional context**
I guess I can see that the problem is I don't have the ability to copy into /usr/local/bin. Should I be trying to figure out a way to put the libraries somewhere else and make a new map to where they are (which I don't know how to do). I have tried installing inside my own new conda environment, however, ultimately, I want to be able to use this with the rubin-evns functionalities. Also, it didn't function.

**this is the full commands and output**

(lsst-scipipe-4.1.0) [ledwar04@nb-ledwar04 homebrew]$ git clone https://github.com/JohannesBuchner/MultiNest
Cloning into 'MultiNest'...
remote: Enumerating objects: 549, done.
remote: Counting objects: 100% (118/118), done.
remote: Compressing objects: 100% (98/98), done.
remote: Total 549 (delta 65), reused 49 (delta 19), pack-reused 431
Receiving objects: 100% (549/549), 300.02 KiB | 3.85 MiB/s, done.
Resolving deltas: 100% (342/342), done.
(lsst-scipipe-4.1.0) [ledwar04@nb-ledwar04 homebrew]$ ls
bin     CHANGELOG.md  CONTRIBUTING.md  docs  include  Library      manpages   opt        sbin   var
Cellar  completions   Dockerfile       etc   lib      LICENSE.txt  MultiNest  README.md  share
(lsst-scipipe-4.1.0) [ledwar04@nb-ledwar04 homebrew]$ pwd
/home/ledwar04/homebrew
(lsst-scipipe-4.1.0) [ledwar04@nb-ledwar04 homebrew]$ cd ..
(lsst-scipipe-4.1.0) [ledwar04@nb-ledwar04 ~]$ ls
BCGList_061522.ipynb                              BrighterFatter       InputFiles             ompi
BFGal_Plots_072922.ipynb                          Companions           lapack                 output
BFGal_Plots_080122-multin-Copy1.ipynb             DATA                 LatexNotWorking.ipynb  SEDfitting
BFGal_Plots_080122-multin-data-already-run.ipynb  exportlibpath        localcode              Structure_2deg_071122.ipynb
BFGal_Plots_080122-singlen.ipynb                  Filaments-Old        LSSTFilters            StructureAroundCluster_072623.ipynb
BFGal_Plots_082322-CreateTable.ipynb              FindLowSBGals.ipynb  MultiNest              tmp
BFresults                                         homebrew             nannomaggie2e.ipynb    Untitled.ipynb
Bias                                              idleculler           notebooks              WORK
(lsst-scipipe-4.1.0) [ledwar04@nb-ledwar04 ~]$ cd MultiNest/
(lsst-scipipe-4.1.0) [ledwar04@nb-ledwar04 MultiNest]$ ls
bin  build  CMakeLists.txt  CMakeModules  include  lib  LICENCE  license.pdf  modules  README  src
(lsst-scipipe-4.1.0) [ledwar04@nb-ledwar04 MultiNest]$ cd build/
(lsst-scipipe-4.1.0) [ledwar04@nb-ledwar04 build]$ ls
README
(lsst-scipipe-4.1.0) [ledwar04@nb-ledwar04 build]$ cd
(lsst-scipipe-4.1.0) [ledwar04@nb-ledwar04 ~]$ export DYLD_LIBRARY_PATH="/usr/local/bin/gcc-4.9:$DYLD_LIBRARY_PATH"
(lsst-scipipe-4.1.0) [ledwar04@nb-ledwar04 ~]$ cd MultiNest/build/
(lsst-scipipe-4.1.0) [ledwar04@nb-ledwar04 build]$ ls
README
(lsst-scipipe-4.1.0) [ledwar04@nb-ledwar04 build]$ cmake ..
-- The Fortran compiler identification is GNU 10.4.0
-- The C compiler identification is GNU 10.4.0
-- The CXX compiler identification is GNU 10.4.0
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Check for working Fortran compiler: /opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-4.1.0/bin/x86_64-conda-linux-gnu-gfortran - skipped
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-4.1.0/bin/x86_64-conda-linux-gnu-cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-4.1.0/bin/x86_64-conda-linux-gnu-c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for Fortran sgemm
-- Looking for Fortran sgemm - not found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Looking for Fortran sgemm
-- Looking for Fortran sgemm - found
-- Found BLAS: /opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-4.1.0/lib/libblas.so  
-- Looking for Fortran cheev
-- Looking for Fortran cheev - found
-- Found LAPACK: /opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-4.1.0/lib/libblas.so;-lpthread;-lm;-ldl  
-- Detected gfortran, adding -ffree-line-length-none compiler flag.
-- Detected gfortran >= 10, adding -std=legacy compiler flag.
-- Detected gfortran-10+, adding -w -fallow-argument-mismatch compiler flag.
-- Found MPI_C: /opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-4.1.0/lib/libmpi.so (found version "3.1") 
-- Found MPI_CXX: /opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-4.1.0/lib/libmpicxx.so (found version "3.1") 
-- Found MPI_Fortran: /opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-4.1.0/lib/libmpifort.so (found version "3.1") 
-- Found MPI: TRUE (found version "3.1")  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ledwar04/MultiNest/build
(lsst-scipipe-4.1.0) [ledwar04@nb-ledwar04 build]$ make
Scanning dependencies of target multinest_static
[  1%] Building Fortran object src/CMakeFiles/multinest_static.dir/utils.f90.o
[  2%] Building Fortran object src/CMakeFiles/multinest_static.dir/utils1.f90.o
[  4%] Building Fortran object src/CMakeFiles/multinest_static.dir/kmeans_clstr.f90.o
[  5%] Building Fortran object src/CMakeFiles/multinest_static.dir/xmeans_clstr.f90.o
[  7%] Building Fortran object src/CMakeFiles/multinest_static.dir/posterior.F90.o
[  8%] Building Fortran object src/CMakeFiles/multinest_static.dir/priors.f90.o
[ 10%] Building Fortran object src/CMakeFiles/multinest_static.dir/nested.F90.o
[ 11%] Building Fortran object src/CMakeFiles/multinest_static.dir/cwrapper.f90.o
[ 12%] Linking Fortran static library /home/ledwar04/MultiNest/lib/libmultinest.a
[ 12%] Built target multinest_static
Scanning dependencies of target multinest_shared
[ 14%] Building Fortran object src/CMakeFiles/multinest_shared.dir/utils.f90.o
[ 15%] Building Fortran object src/CMakeFiles/multinest_shared.dir/utils1.f90.o
[ 17%] Building Fortran object src/CMakeFiles/multinest_shared.dir/kmeans_clstr.f90.o
[ 18%] Building Fortran object src/CMakeFiles/multinest_shared.dir/xmeans_clstr.f90.o
[ 20%] Building Fortran object src/CMakeFiles/multinest_shared.dir/posterior.F90.o
[ 21%] Building Fortran object src/CMakeFiles/multinest_shared.dir/priors.f90.o
[ 22%] Building Fortran object src/CMakeFiles/multinest_shared.dir/nested.F90.o
[ 24%] Building Fortran object src/CMakeFiles/multinest_shared.dir/cwrapper.f90.o
[ 25%] Linking Fortran shared library /home/ledwar04/MultiNest/lib/libmultinest.so
[ 25%] Built target multinest_shared
Scanning dependencies of target multinest_mpi_static
[ 27%] Building Fortran object src/CMakeFiles/multinest_mpi_static.dir/utils.f90.o
[ 28%] Building Fortran object src/CMakeFiles/multinest_mpi_static.dir/utils1.f90.o
[ 30%] Building Fortran object src/CMakeFiles/multinest_mpi_static.dir/kmeans_clstr.f90.o
[ 31%] Building Fortran object src/CMakeFiles/multinest_mpi_static.dir/xmeans_clstr.f90.o
[ 32%] Building Fortran object src/CMakeFiles/multinest_mpi_static.dir/posterior.F90.o
[ 34%] Building Fortran object src/CMakeFiles/multinest_mpi_static.dir/priors.f90.o
[ 35%] Building Fortran object src/CMakeFiles/multinest_mpi_static.dir/nested.F90.o
[ 37%] Building Fortran object src/CMakeFiles/multinest_mpi_static.dir/cwrapper.f90.o
[ 38%] Linking Fortran static library /home/ledwar04/MultiNest/lib/libmultinest_mpi.a
[ 38%] Built target multinest_mpi_static
Scanning dependencies of target multinest_mpi_shared
[ 40%] Building Fortran object src/CMakeFiles/multinest_mpi_shared.dir/utils.f90.o
[ 41%] Building Fortran object src/CMakeFiles/multinest_mpi_shared.dir/utils1.f90.o
[ 42%] Building Fortran object src/CMakeFiles/multinest_mpi_shared.dir/kmeans_clstr.f90.o
[ 44%] Building Fortran object src/CMakeFiles/multinest_mpi_shared.dir/xmeans_clstr.f90.o
[ 45%] Building Fortran object src/CMakeFiles/multinest_mpi_shared.dir/posterior.F90.o
[ 47%] Building Fortran object src/CMakeFiles/multinest_mpi_shared.dir/priors.f90.o
[ 48%] Building Fortran object src/CMakeFiles/multinest_mpi_shared.dir/nested.F90.o
[ 50%] Building Fortran object src/CMakeFiles/multinest_mpi_shared.dir/cwrapper.f90.o
[ 51%] Linking Fortran shared library /home/ledwar04/MultiNest/lib/libmultinest_mpi.so
[ 51%] Built target multinest_mpi_shared
Scanning dependencies of target ackley
[ 52%] Building Fortran object src/example_ackley/CMakeFiles/ackley.dir/params.f90.o
[ 54%] Building Fortran object src/example_ackley/CMakeFiles/ackley.dir/like.f90.o
[ 55%] Building Fortran object src/example_ackley/CMakeFiles/ackley.dir/nestwrap.f90.o
[ 57%] Building Fortran object src/example_ackley/CMakeFiles/ackley.dir/main.f90.o
[ 58%] Linking Fortran executable /home/ledwar04/MultiNest/bin/ackley
[ 58%] Built target ackley
[ 60%] Building C object src/example_eggbox_C/CMakeFiles/eggboxC.dir/eggbox.c.o
[ 61%] Linking C executable /home/ledwar04/MultiNest/bin/eggboxC
[ 61%] Built target eggboxC
[ 62%] Building CXX object src/example_eggbox_C++/CMakeFiles/eggboxC++.dir/eggbox.cc.o
[ 64%] Linking CXX executable /home/ledwar04/MultiNest/bin/eggboxC++
[ 64%] Built target eggboxC++
Scanning dependencies of target gaussian
[ 65%] Building Fortran object src/example_gaussian/CMakeFiles/gaussian.dir/params.f90.o
[ 67%] Building Fortran object src/example_gaussian/CMakeFiles/gaussian.dir/like.f90.o
[ 68%] Building Fortran object src/example_gaussian/CMakeFiles/gaussian.dir/nestwrap.f90.o
[ 70%] Building Fortran object src/example_gaussian/CMakeFiles/gaussian.dir/main.f90.o
[ 71%] Linking Fortran executable /home/ledwar04/MultiNest/bin/gaussian
[ 71%] Built target gaussian
Scanning dependencies of target gauss_shell
[ 72%] Building Fortran object src/example_gauss_shell/CMakeFiles/gauss_shell.dir/params.f90.o
[ 74%] Building Fortran object src/example_gauss_shell/CMakeFiles/gauss_shell.dir/like.f90.o
[ 75%] Building Fortran object src/example_gauss_shell/CMakeFiles/gauss_shell.dir/nestwrap.f90.o
[ 77%] Building Fortran object src/example_gauss_shell/CMakeFiles/gauss_shell.dir/main.f90.o
[ 78%] Linking Fortran executable /home/ledwar04/MultiNest/bin/gauss_shell
[ 78%] Built target gauss_shell
Scanning dependencies of target himmelblau
[ 80%] Building Fortran object src/example_himmelblau/CMakeFiles/himmelblau.dir/params.f90.o
[ 81%] Building Fortran object src/example_himmelblau/CMakeFiles/himmelblau.dir/like.f90.o
[ 82%] Building Fortran object src/example_himmelblau/CMakeFiles/himmelblau.dir/nestwrap.f90.o
[ 84%] Building Fortran object src/example_himmelblau/CMakeFiles/himmelblau.dir/main.f90.o
[ 85%] Linking Fortran executable /home/ledwar04/MultiNest/bin/himmelblau
[ 85%] Built target himmelblau
Scanning dependencies of target obj_detect
[ 87%] Building Fortran object src/example_obj_detect/CMakeFiles/obj_detect.dir/params.f90.o
[ 88%] Building Fortran object src/example_obj_detect/CMakeFiles/obj_detect.dir/like.f90.o
[ 90%] Building Fortran object src/example_obj_detect/CMakeFiles/obj_detect.dir/nestwrap.f90.o
[ 91%] Building Fortran object src/example_obj_detect/CMakeFiles/obj_detect.dir/main.f90.o
[ 92%] Linking Fortran executable /home/ledwar04/MultiNest/bin/obj_detect
[ 92%] Built target obj_detect
Scanning dependencies of target rosenbrock
[ 94%] Building Fortran object src/example_rosenbrock/CMakeFiles/rosenbrock.dir/params.f90.o
[ 95%] Building Fortran object src/example_rosenbrock/CMakeFiles/rosenbrock.dir/like.f90.o
[ 97%] Building Fortran object src/example_rosenbrock/CMakeFiles/rosenbrock.dir/nestwrap.f90.o
[ 98%] Building Fortran object src/example_rosenbrock/CMakeFiles/rosenbrock.dir/main.f90.o
[100%] Linking Fortran executable /home/ledwar04/MultiNest/bin/rosenbrock
[100%] Built target rosenbrock
(lsst-scipipe-4.1.0) [ledwar04@nb-ledwar04 build]$ sudo install make
bash: sudo: command not found
(lsst-scipipe-4.1.0) [ledwar04@nb-ledwar04 build]$ install make
install: missing destination file operand after ‘make’
Try 'install --help' for more information.
(lsst-scipipe-4.1.0) [ledwar04@nb-ledwar04 build]$ make install
[ 12%] Built target multinest_static
[ 25%] Built target multinest_shared
[ 38%] Built target multinest_mpi_static
[ 51%] Built target multinest_mpi_shared
[ 58%] Built target ackley
Consolidate compiler generated dependencies of target eggboxC
[ 61%] Built target eggboxC
Consolidate compiler generated dependencies of target eggboxC++
[ 64%] Built target eggboxC++
[ 71%] Built target gaussian
[ 78%] Built target gauss_shell
[ 85%] Built target himmelblau
[ 92%] Built target obj_detect
[100%] Built target rosenbrock
Install the project...
-- Install configuration: ""
-- Installing: /usr/local/lib/libmultinest.a
CMake Error at src/cmake_install.cmake:46 (file):
  file INSTALL cannot copy file "/home/ledwar04/MultiNest/lib/libmultinest.a"
  to "/usr/local/lib/libmultinest.a": Permission denied.
Call Stack (most recent call first):
  cmake_install.cmake:47 (include)

make: *** [Makefile:100: install] Error 1
(lsst-scipipe-4.1.0) [ledwar04@nb-ledwar04 build]$ sudo make install
bash: sudo: command not found
(lsst-scipipe-4.1.0) [ledwar04@nb-ledwar04 build]$

**Comment by MelissaGraham** [comment]
Hi @ledwar04, I asked around a bit and one RSP team member offered a quick guess: LD_LIBRARY_PATH has to be set somewhere in local_setup, not (just) bashrc. Perhaps try that as a first test?

**Comment by frossie** [comment]
Did @ledwar04 do this test?

**Comment by DouglasLeeTucker** [comment]
Hi Louise,

@leannep just created a very nice notebook to deal with this issue.  I reviewed it, going step-by-step, and it works nicely.  It can be found here:  https://github.com/rubin-dp0/tutorial-notebooks/blob/main/DP02_20_Working_with_user_packages.ipynb

I know I am going to be making use of this method myself!  

I hope this helps!  Let us know if it doesn't!

Best regards,
Douglas

PS:  I believe @ryanlauastro has also sent you a direct message about this same notebook.

**Comment by DouglasLeeTucker** [comment]
Oops -- that link is broken.  Try this instead:
https://github.com/rubin-dp0/tutorial-notebooks/blob/main/DP02_11_Working_with_user_packages.ipynb

It will soon be moved from main to prod and appear in your https:/data.lsst.cloud/ notebook directory.

If you can't access that info just yet, here is a summary of Leanne's notebook:

Open a terminal in the RSP to execute the following commands:
> pip install --user bagpipes
> mkdir ~/local
> cd ~/local
> git clone https://github.com/JohannesBuchner/MultiNest
> cd MultiNest/build
> cmake ..
> make

The LD_LIBRARY_PATH environment variable must now be updated.
To test in the RSP terminal window, try:
> export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${HOME}/local/MultiNest/lib
> python -c 'import bagpipes as pipes'

This should work, or only result in a warning about LaTeX issues.

If it does, you can update your .bashrc file and your notebooks/.user_setups file by adding the following line to each:
`export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${HOME}/local/MultiNest/lib`

You will need to log out and log back in again before you trying using `bagpipes` in an RSP Jupyter notebook.
Once you do, you can run the following in an RSP notebook:
> import os
> print(os.getenv('LD_LIBRARY_PATH'))
> import bagpipes as pipes

I tried it myself, and it worked; so give it a try yourself!  
Let us know if you continue to have issues.  
Thanks!

**Comment by MelissaGraham** [comment]
Thanks Douglas.

@ledwar04, whenever you get back to this, if the above advice works let us know so we can close this ticket.

**Comment by ledwar04** [comment]
Oh my gosh!

Wow, this will be a super duper helpful tutorial - my group has been pip installing packages all summer 😉

I have moved on to using Dense Basis (which installed really well) instead of Bagpipes - but I can take a moment to test this, and close the ticket - absolutely! Hopefully okay if it takes me a week or two to get to it -
l.
________________________________

**Comment by ledwar04** [comment]
Hmm, unfortunately this did not work.

I got the following error when I try the command:

python -c 'import bagpipes as pipes'

from part 1.3 of the tutorial.

The error is below:

***@***.*** ~]$ python -c 'import bagpipes as pipes'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ledwar04/.local/lib/python3.10/site-packages/bagpipes/__init__.py", line 3, in <module>
    from . import models
  File "/home/ledwar04/.local/lib/python3.10/site-packages/bagpipes/models/__init__.py", line 3, in <module>
    from . import making
  File "/home/ledwar04/.local/lib/python3.10/site-packages/bagpipes/models/making/__init__.py", line 4, in <module>
    from . import make_cloudy_models
  File "/home/ledwar04/.local/lib/python3.10/site-packages/bagpipes/models/making/make_cloudy_models.py", line 12, in <module>
    from ..model_galaxy import model_galaxy
  File "/home/ledwar04/.local/lib/python3.10/site-packages/bagpipes/models/model_galaxy.py", line 5, in <module>
    import spectres
  File "/home/ledwar04/.local/lib/python3.10/site-packages/spectres/__init__.py", line 4, in <module>
    import numba
  File "/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-6.0.0/lib/python3.10/site-packages/numba/__init__.py", line 42, in <module>
    from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
  File "/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-6.0.0/lib/python3.10/site-packages/numba/np/ufunc/__init__.py", line 3, in <module>
    from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
  File "/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-6.0.0/lib/python3.10/site-packages/numba/np/ufunc/decorators.py", line 3, in <module>
    from numba.np.ufunc import _internal
SystemError: initialization of _internal failed without raising an exception




Louise
________________________________

**Comment by DouglasLeeTucker** [comment]
Dear Louise,

You might need to log out and re-login to the RSP for it to work.
If that doesn’t work, we can try to go at an upcoming Stack Club or DP0 meeting, or maybe even an ad hoc Zoom session.
Let us know if you still have trouble with it!
Thanks!

Best regards,
Douglas


From: Louise Edwards ***@***.***>
Date: Tuesday, August 1, 2023 at 3:03 PM
To: rubin-dp0/Support ***@***.***>
Cc: Douglas L Tucker ***@***.***>, Comment ***@***.***>
Subject: Re: [rubin-dp0/Support] Unable to point to MultiNest package libraries within notebook (Issue #39)
Hmm, unfortunately this did not work.

I got the following error when I try the command:

python -c 'import bagpipes as pipes'

from part 1.3 of the tutorial.

The error is below:

***@***.*** ~]$ python -c 'import bagpipes as pipes'
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/home/ledwar04/.local/lib/python3.10/site-packages/bagpipes/__init__.py", line 3, in <module>
from . import models
File "/home/ledwar04/.local/lib/python3.10/site-packages/bagpipes/models/__init__.py", line 3, in <module>
from . import making
File "/home/ledwar04/.local/lib/python3.10/site-packages/bagpipes/models/making/__init__.py", line 4, in <module>
from . import make_cloudy_models
File "/home/ledwar04/.local/lib/python3.10/site-packages/bagpipes/models/making/make_cloudy_models.py", line 12, in <module>
from ..model_galaxy import model_galaxy
File "/home/ledwar04/.local/lib/python3.10/site-packages/bagpipes/models/model_galaxy.py", line 5, in <module>
import spectres
File "/home/ledwar04/.local/lib/python3.10/site-packages/spectres/__init__.py", line 4, in <module>
import numba
File "/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-6.0.0/lib/python3.10/site-packages/numba/__init__.py", line 42, in <module>
from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
File "/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-6.0.0/lib/python3.10/site-packages/numba/np/ufunc/__init__.py", line 3, in <module>
from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
File "/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-6.0.0/lib/python3.10/site-packages/numba/np/ufunc/decorators.py", line 3, in <module>
from numba.np.ufunc import _internal
SystemError: initialization of _internal failed without raising an exception




Louise
________________________________

**Comment by MelissaGraham** [comment]
@ledwar04 and @DouglasLeeTucker, could you confirm that this issue has been resolved and that this ticket can be closed?

**Comment by ledwar04** [comment]
Yes, I confirm.
l.
________________________________

**Comment by MelissaGraham** [comment]
Thank you! Closing issue.

**Comment by DouglasLeeTucker** [comment]
Thanks, @MelissaGraham !  Thanks, @ledwar04 !
